/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPosRouteImport } from './routes/admin.pos'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin.purchase-orders'
import { Route as AdminReconciliationRouteImport } from './routes/admin.reconciliation'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AdminFinanceCashFlowRouteImport } from './routes/admin.finance.cash-flow'
import { Route as AdminFinanceInvoicesRouteImport } from './routes/admin.finance.invoices'
import { Route as AdminFinanceProfitLossRouteImport } from './routes/admin.finance.profit-loss'
import { Route as AdminFinanceTaxRouteImport } from './routes/admin.finance.tax'
import { Route as AdminOpsActivityRouteImport } from './routes/admin.ops.activity'
import { Route as AdminOpsCalendarRouteImport } from './routes/admin.ops.calendar'
import { Route as AdminOpsContentRouteImport } from './routes/admin.ops.content'
import { Route as AdminOpsStaffRouteImport } from './routes/admin.ops.staff'
import { Route as AdminOpsTasksRouteImport } from './routes/admin.ops.tasks'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliationRoute = AdminReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminFinanceCashFlowRoute = AdminFinanceCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceInvoicesRoute = AdminFinanceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceProfitLossRoute = AdminFinanceProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceTaxRoute = AdminFinanceTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminOpsActivityRoute = AdminOpsActivityRouteImport.update({
  id: '/ops/activity',
  path: '/ops/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsCalendarRoute = AdminOpsCalendarRouteImport.update({
  id: '/ops/calendar',
  path: '/ops/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsContentRoute = AdminOpsContentRouteImport.update({
  id: '/ops/content',
  path: '/ops/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsStaffRoute = AdminOpsStaffRouteImport.update({
  id: '/ops/staff',
  path: '/ops/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsTasksRoute = AdminOpsTasksRouteImport.update({
  id: '/ops/tasks',
  path: '/ops/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/finance/cash-flow': typeof AdminFinanceCashFlowRoute
  '/admin/finance/invoices': typeof AdminFinanceInvoicesRoute
  '/admin/finance/profit-loss': typeof AdminFinanceProfitLossRoute
  '/admin/finance/tax': typeof AdminFinanceTaxRoute
  '/admin/ops/activity': typeof AdminOpsActivityRoute
  '/admin/ops/calendar': typeof AdminOpsCalendarRoute
  '/admin/ops/content': typeof AdminOpsContentRoute
  '/admin/ops/staff': typeof AdminOpsStaffRoute
  '/admin/ops/tasks': typeof AdminOpsTasksRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/finance/cash-flow': typeof AdminFinanceCashFlowRoute
  '/admin/finance/invoices': typeof AdminFinanceInvoicesRoute
  '/admin/finance/profit-loss': typeof AdminFinanceProfitLossRoute
  '/admin/finance/tax': typeof AdminFinanceTaxRoute
  '/admin/ops/activity': typeof AdminOpsActivityRoute
  '/admin/ops/calendar': typeof AdminOpsCalendarRoute
  '/admin/ops/content': typeof AdminOpsContentRoute
  '/admin/ops/staff': typeof AdminOpsStaffRoute
  '/admin/ops/tasks': typeof AdminOpsTasksRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/shop': typeof ShopRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/pos': typeof AdminPosRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/finance/cash-flow': typeof AdminFinanceCashFlowRoute
  '/admin/finance/invoices': typeof AdminFinanceInvoicesRoute
  '/admin/finance/profit-loss': typeof AdminFinanceProfitLossRoute
  '/admin/finance/tax': typeof AdminFinanceTaxRoute
  '/admin/ops/activity': typeof AdminOpsActivityRoute
  '/admin/ops/calendar': typeof AdminOpsCalendarRoute
  '/admin/ops/content': typeof AdminOpsContentRoute
  '/admin/ops/staff': typeof AdminOpsStaffRoute
  '/admin/ops/tasks': typeof AdminOpsTasksRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/shop'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/reconciliation'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/category/$slug'
    | '/product/$id'
    | '/admin/'
    | '/admin/customers/$id'
    | '/admin/finance/cash-flow'
    | '/admin/finance/invoices'
    | '/admin/finance/profit-loss'
    | '/admin/finance/tax'
    | '/admin/ops/activity'
    | '/admin/ops/calendar'
    | '/admin/ops/content'
    | '/admin/ops/staff'
    | '/admin/ops/tasks'
    | '/admin/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/shop'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/reconciliation'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/category/$slug'
    | '/product/$id'
    | '/admin'
    | '/admin/customers/$id'
    | '/admin/finance/cash-flow'
    | '/admin/finance/invoices'
    | '/admin/finance/profit-loss'
    | '/admin/finance/tax'
    | '/admin/ops/activity'
    | '/admin/ops/calendar'
    | '/admin/ops/content'
    | '/admin/ops/staff'
    | '/admin/ops/tasks'
    | '/admin/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/shop'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/orders'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/purchase-orders'
    | '/admin/reconciliation'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/category/$slug'
    | '/product/$id'
    | '/admin/'
    | '/admin/customers/$id'
    | '/admin/finance/cash-flow'
    | '/admin/finance/invoices'
    | '/admin/finance/profit-loss'
    | '/admin/finance/tax'
    | '/admin/ops/activity'
    | '/admin/ops/calendar'
    | '/admin/ops/content'
    | '/admin/ops/staff'
    | '/admin/ops/tasks'
    | '/admin/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ShopRoute: typeof ShopRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reconciliation': {
      id: '/admin/reconciliation'
      path: '/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AdminReconciliationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/finance/cash-flow': {
      id: '/admin/finance/cash-flow'
      path: '/cash-flow'
      fullPath: '/admin/finance/cash-flow'
      preLoaderRoute: typeof AdminFinanceCashFlowRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/invoices': {
      id: '/admin/finance/invoices'
      path: '/invoices'
      fullPath: '/admin/finance/invoices'
      preLoaderRoute: typeof AdminFinanceInvoicesRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/profit-loss': {
      id: '/admin/finance/profit-loss'
      path: '/profit-loss'
      fullPath: '/admin/finance/profit-loss'
      preLoaderRoute: typeof AdminFinanceProfitLossRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/tax': {
      id: '/admin/finance/tax'
      path: '/tax'
      fullPath: '/admin/finance/tax'
      preLoaderRoute: typeof AdminFinanceTaxRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/ops/activity': {
      id: '/admin/ops/activity'
      path: '/ops/activity'
      fullPath: '/admin/ops/activity'
      preLoaderRoute: typeof AdminOpsActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/calendar': {
      id: '/admin/ops/calendar'
      path: '/ops/calendar'
      fullPath: '/admin/ops/calendar'
      preLoaderRoute: typeof AdminOpsCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/content': {
      id: '/admin/ops/content'
      path: '/ops/content'
      fullPath: '/admin/ops/content'
      preLoaderRoute: typeof AdminOpsContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/staff': {
      id: '/admin/ops/staff'
      path: '/ops/staff'
      fullPath: '/admin/ops/staff'
      preLoaderRoute: typeof AdminOpsStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/tasks': {
      id: '/admin/ops/tasks'
      path: '/ops/tasks'
      fullPath: '/admin/ops/tasks'
      preLoaderRoute: typeof AdminOpsTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminFinanceRouteChildren {
  AdminFinanceCashFlowRoute: typeof AdminFinanceCashFlowRoute
  AdminFinanceInvoicesRoute: typeof AdminFinanceInvoicesRoute
  AdminFinanceProfitLossRoute: typeof AdminFinanceProfitLossRoute
  AdminFinanceTaxRoute: typeof AdminFinanceTaxRoute
}

const AdminFinanceRouteChildren: AdminFinanceRouteChildren = {
  AdminFinanceCashFlowRoute: AdminFinanceCashFlowRoute,
  AdminFinanceInvoicesRoute: AdminFinanceInvoicesRoute,
  AdminFinanceProfitLossRoute: AdminFinanceProfitLossRoute,
  AdminFinanceTaxRoute: AdminFinanceTaxRoute,
}

const AdminFinanceRouteWithChildren = AdminFinanceRoute._addFileChildren(
  AdminFinanceRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminFinanceRoute: typeof AdminFinanceRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPosRoute: typeof AdminPosRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRoute
  AdminReconciliationRoute: typeof AdminReconciliationRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOpsActivityRoute: typeof AdminOpsActivityRoute
  AdminOpsCalendarRoute: typeof AdminOpsCalendarRoute
  AdminOpsContentRoute: typeof AdminOpsContentRoute
  AdminOpsStaffRoute: typeof AdminOpsStaffRoute
  AdminOpsTasksRoute: typeof AdminOpsTasksRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminFinanceRoute: AdminFinanceRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPosRoute: AdminPosRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRoute,
  AdminReconciliationRoute: AdminReconciliationRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOpsActivityRoute: AdminOpsActivityRoute,
  AdminOpsCalendarRoute: AdminOpsCalendarRoute,
  AdminOpsContentRoute: AdminOpsContentRoute,
  AdminOpsStaffRoute: AdminOpsStaffRoute,
  AdminOpsTasksRoute: AdminOpsTasksRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ShopRoute: ShopRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
